In [1]:
import pandas as pd
movies = pd.read_csv('movies.csv')
split_co = movies['production_companies'].str.split('|', expand=True)
split_co['id'] = movies['id']
merged_back = movies.merge(split_co)

In [2]:
merged_back.head(3)

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,vote_count,vote_average,release_year,budget_adj,revenue_adj,0,1,2,3,4
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,5562,6.5,2015,1.379999e+08,1.392446e+09,Universal Studios,Amblin Entertainment,Legendary Pictures,Fuji Television Network,Dentsu
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,6185,7.1,2015,1.379999e+08,3.481613e+08,Village Roadshow Pictures,Kennedy Miller Productions,None,None,None
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,2480,6.3,2015,1.012000e+08,2.716190e+08,Summit Entertainment,Mandeville Films,Red Wagon Entertainment,NeoReel,None

In [3]:
melted = pd.melt(
    merged_back, id_vars=['id','revenue'], 
    value_vars=[0, 1, 2, 3, 4], value_name='production_companies'
).drop('variable', axis = 1
).dropna()
melted.to_csv('id_production_companies.csv', index=False)

In [4]:
melted.head

<bound method DataFrame.head of            id     revenue                    production_companies
0      135397  1513528810                       Universal Studios
1       76341   378436354               Village Roadshow Pictures
2      262500   295238201                    Summit Entertainment
3      140607  2068178225                               Lucasfilm
4      168259  1506249360                      Universal Pictures
5      281957   532950503                     Regency Enterprises
6       87101   440603537                      Paramount Pictures
7      286217   595380321  Twentieth Century Fox Film Corporation
8      211672  1156730962                      Universal Pictures
9      150540   853708609                    Walt Disney Pictures
10     206647   880674609                       Columbia Pictures
11      76757   183987723               Village Roadshow Pictures
12     264660    36869414                               DNA Films
13     257344   243637091                       Columbia Pictures
14      99861  1405035767                          Marvel Studios
15     273248   155760117                    Double Feature Films
16     260346   325771424  Twentieth Century Fox Film Corporation
17     102899   518602163                          Marvel Studios
18     150689   542351353                    Walt Disney Pictures
19     131634   650523427                       Studio Babelsberg
20     158852   209035668                    Walt Disney Pictures
21     307081    91709827                          Escape Artists
22     254128   470490832                         New Line Cinema
23     216015   569651467                          Focus Features
24     318846   133346506                      Paramount Pictures
25     177677   682330139                      Paramount Pictures
26     214756   215863606                      Universal Pictures
27     207703   403802136  Twentieth Century Fox Film Corporation
28     314365    88346473                       Participant Media
29     294254   311256926                            Gotham Group
...       ...         ...                                     ...
52423   47886     1198346                              Fort Films
52448     857   481840909                 Mark Gordon Productions
52471     929   379014294                             Fried Films
52472    6435    46683377                        Stargate Studios
52475    1878    10680275                       Shark Productions
52481     795   198685114                             Taurus Film
52501    9424    17507368     Behavioral Problem Productions Ltd.
52504     100     3897569                 The Steve Tisch Company
52513    9945           0                Spooky Tooth Productions
52533   11258    19870567                                Marubeni
52584    8129           0                       Parallax Pictures
52609   37498           0                 Val D'Oro Entertainment
52791     280   520000000                          T2 Productions
52820   12627           0             George Reinhart Productions
52822     339     2015810                          Pandora Cinema
52863   20978           0           Paravision International S.A.
53068     106    98235548                          Amercent Films
53086     746    43984230                                TAO Film
53130   17238           0                                 Mondial
53138   39507           0                            Liffey Films
53190   39929     2683519                                TBA Film
53249   16938           0                            August Films
53679    8446           0                Bugsy Malone Productions
53695    9479    75634409                     Touchstone Pictures
53708    9350   255000211                 Cliffhanger Productions
53721    9607    20844907                                Nintendo
53741    1634   153698625        Donner/Shuler-Donner Productions
53781    2259           6                    Neue Constantin Film
53981   11416    17218023              Kingsmere Productions Ltd.
54043   13853           0                       The Jozak Company

[23231 rows x 3 columns]>

In [12]:
new_df = melted[melted['production_companies'].isin(["Universal Pictures", "Paramount Pictures"])]
new_df.to_csv('Universal_Paramount.csv', index=False)

In [13]:
new_df

           id production_companies
4      168259   Universal Pictures
6       87101   Paramount Pictures
8      211672   Universal Pictures
24     318846   Paramount Pictures
25     177677   Paramount Pictures
26     214756   Universal Pictures
32     254470   Universal Pictures
42     321697   Universal Pictures
52     253412   Universal Pictures
59     201088   Universal Pictures
69     271718   Universal Pictures
91     274167   Paramount Pictures
102    241251   Universal Pictures
106    273477   Paramount Pictures
110    287903   Universal Pictures
116    297291   Universal Pictures
118    227719   Paramount Pictures
124    146301   Paramount Pictures
129    228165   Paramount Pictures
211    243938   Paramount Pictures
287    266639   Universal Pictures
416    347754   Universal Pictures
428    343934   Paramount Pictures
629    157336   Paramount Pictures
644    240832   Universal Pictures
645     98566   Paramount Pictures
648     91314   Paramount Pictures
662    242512   Universal Pictures
671     49017   Universal Pictures
681    238636   Universal Pictures
...       ...                  ...
18753      87   Paramount Pictures
18946     568   Universal Pictures
19193   11259   Universal Pictures
19245      85   Paramount Pictures
19350    9327   Universal Pictures
19361   10779   Universal Pictures
19397   10543   Universal Pictures
19456    6346   Universal Pictures
19458    9099   Universal Pictures
19531      98   Universal Pictures
19533    8871   Universal Pictures
19552    1597   Universal Pictures
19630   12107   Universal Pictures
19872    1934   Universal Pictures
19923    8838   Universal Pictures
19955   11252   Universal Pictures
20050      89   Paramount Pictures
20080    1552   Universal Pictures
20246   28597   Universal Pictures
20428   28176   Paramount Pictures
20891    9768   Universal Pictures
20909     951   Universal Pictures
20927   11077   Universal Pictures
21221   12574   Universal Pictures
21476     838   Universal Pictures
24384     453   Universal Pictures
25150   49849   Universal Pictures
25758    9266   Universal Pictures
26735   10588   Universal Pictures
27985     921   Universal Pictures

[953 rows x 2 columns]